security: controller: all: add missing request-map security elems
Patches most controllers (except admin) to avoid having requests that
omit the security element, and set logical/preexisting https/auth
settings instead. In most cases these were omissions and leave question
marks.

EXCEPTION: admin requests - either just tests or need separate review
for auth setting.

Refs https://gitlab.ilscipio.com/scipio-dev/dev/scipioce-dev/issues/31